'use strict';
const $=s=>document.querySelector(s);const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=(n,cls='icon')=>`<img class="${cls}" src="assets/icons/${n}.svg" alt="">`;
let library,city='杭州',scope='hangzhou',limit=12,lastFocus;const detailDialog=$('#detail-dialog'),utilityDialog=$('#utility-dialog');
const claims=(r,k)=>r.evidence.flatMap(e=>e.fields.filter(f=>f.key===k).map(f=>f.value));
const words=r=>[r.name,r.type,r.area,...r.tags,...r.aliases,...r.evidence.flatMap(e=>e.fields.map(f=>f.value))].join(' ');
function filtered(){if(city!=='杭州')return[];let q=$('#query').value.trim().toLowerCase(),env=$('#environment').value,people=$('#audience').value,budget=$('#budget').value,facility=$('#facility').value;let rows=library.records.filter(r=>r.scope===scope&&(!q||words(r).toLowerCase().includes(q))&&(!env||new RegExp(env).test(words(r)))&&(!people||new RegExp(people).test(claims(r,'audience').join(' ')))&&(!facility||claims(r,facility).some(v=>!/^未|^待|未核实/.test(v)))&&(!budget||(budget==='free'?claims(r,'fee').some(x=>/免费/.test(x)):budget==='priced'?claims(r,'fee').some(x=>/\d|免费/.test(x)):!claims(r,'fee').some(x=>/\d|免费/.test(x)))));let sorting=$('#sort').value;return rows.sort((a,b)=>sorting==='sources'?b.sourceIds.length-a.sourceIds.length:sorting==='newest'?b.lastCollected.localeCompare(a.lastCollected):((a.name==='铜鉴湖公园'?-3:a.name==='青年林'?-2:a.hasDetails?-1:0)-(b.name==='铜鉴湖公园'?-3:b.name==='青年林'?-2:b.hasDetails?-1:0)));}
function photos(r){let imgs=(r.images||[]).filter(x=>x.url&&x.permission==='allowed').slice(0,9);return imgs.length?imgs:[{url:/树林|森林|林间|树荫/.test(r.tags.join(' '))?'assets/forest.jpg':/湖|水库|江|溪|水边/.test(r.tags.join(' '))?'assets/lake.jpg':'assets/forest.jpg',illustration:true,label:'AI 环境示意 · 非营地实拍'}];}
function fee(r){let v=claims(r,'fee').join('；');if(/免费/.test(v)&&!/\d/.test(v))return /收费/.test(v)&&!/不收费|无收费|未收费/.test(v)?'部分区域免费':'有免费线索';let m=v.match(/(?:¥|￥)?\s*\d+(?:[—–~-]\d+)?\s*(?:元|块)(?:\s*[/／]\s*(?:人|位|天|晚|车|顶))?/);return m?'费用见原文':'预算待核实';}
function facility(r,k,label,ico){let values=claims(r,k).filter(v=>!/^未|^待|未核实/.test(v));let has=values.length>0,reported=k==='toilet'&&has&&values.some(v=>/有|旁/.test(v)&&!/没有|无厕所/.test(v));return `<div class="facility"><div class="facility-label">${icon(ico)}${label}</div><div class="facility-state ${reported?'reported':''}">${icon(reported?'circle-check-filled':'help-circle-filled')}${reported?'作者称有':has?'见原文':'待核实'}</div></div>`;}
function render(){if(!library)return;let rows=filtered();$('#result-count').textContent=`${rows.length}处${scope==='hangzhou'?'营地线索':'周边线索'}`;$('#cards').innerHTML=rows.slice(0,limit).map(r=>{let imgs=photos(r);return `<article class="camp-card"><div class="media"><div class="slides" data-slides="${r.id}">${imgs.map((p,i)=>`<button class="photo-button" data-album="${r.id}" data-index="${i}" aria-label="查看${esc(r.name)}${p.illustration?'示意图':'照片'}"><img src="${esc(p.url)}" alt="${esc(p.illustration?'AI 生成的露营环境示意，并非该营地实拍':r.name+'营地照片')}" loading="${r===rows[0]?'eager':'lazy'}"></button>`).join('')}</div><button class="weather-badge" data-weather="${r.id}">${icon('cloud')}天气待接入</button><span class="image-label">${imgs[0].illustration?'AI 示意 · 非实拍':'营地照片'}</span><span class="image-count">${icon('photo')}<span data-counter="${r.id}">1/${imgs.length}</span></span></div><div class="card-main"><div class="name-row"><h2>${esc(r.name)}</h2><span class="camp-kind">${esc(r.type==='公园与绿地'?'公园绿地':r.type==='自然与乡村地点'?'自然地点':r.type==='待分类'?'类型待核':r.type)}</span></div><div class="rating-row"><span class="rating">${icon('star-filled')}推荐 待评</span><span class="trust">可信度：待核</span></div><p class="environment">${esc(r.tags.length?r.tags.slice(0,3).join(' · '):r.hasDetails?'环境信息见详情':'环境 · 待补充')}</p><div class="cost-route"><div class="cost">${icon('coin-yuan')}<div class="cost-text"><strong>${esc(fee(r))}</strong><small>${/\d|免费|原文/.test(fee(r))?'来源口径 · 见详情':'自带装备 · 费用待核'}</small></div></div><div class="route">${icon('map-pin')}距离 · 车程待核</div></div><div class="facilities">${facility(r,'toilet','厕所','toilet-paper')}${facility(r,'overnight','过夜','tent')}${facility(r,'stove','卡式炉','cooker')}</div><button class="detail-button" data-open="${r.id}" aria-label="查看${esc(r.name)}详情">查看详情${icon('chevron-right')}</button></div></article>`}).join('');$('#empty').hidden=rows.length!==0;$('#empty-title').textContent=city==='杭州'?'没有匹配的地点':city+'资料尚未开放';$('#empty-copy').textContent=city==='杭州'?'换个关键词，或清除筛选再看看。':'目前先整理杭州，后续再扩展其他城市。';$('#load-more').hidden=rows.length<=limit;$('#load-more').textContent=`再看 ${Math.min(12,rows.length-limit)} 处`;document.querySelectorAll('.filters select').forEach(s=>s.classList.toggle('active',!!s.value));document.querySelectorAll('[data-slides]').forEach(s=>s.addEventListener('scroll',()=>{$(`[data-counter="${s.dataset.slides}"]`).textContent=`${Math.round(s.scrollLeft/s.clientWidth)+1}/${s.children.length}`},{passive:true}));}
function panel(title,html){lastFocus=document.activeElement;$('#utility-title').textContent=title;$('#utility-content').innerHTML=html;utilityDialog.showModal();document.body.classList.add('dialog-open');utilityDialog.scrollTop=0;}
function weather(id){let r=library.records.find(r=>r.id===id);panel(r.name+' · 营地天气','<p class="panel-note">天气暂无数据。营地准确坐标与天气服务尚未接入，当前和未来7天预报均待补充。</p><p>首页示意图不代表现场天气，也不代表实时拍摄。</p>');}
function season(id){let r=library.records.find(r=>r.id===id),v=claims(r,'season');panel(r.name+' · 观景季节',v.length?'<p>'+v.map(esc).join('</p><p>')+'</p><p class="panel-note">以上为来源中的季节线索，具体年份、花期与观景条件请以原文为准。</p>':'<p class="panel-note">推荐季节尚待核实。示意图中的绿叶、光线与草地不作为最佳季节依据。</p>');}
function album(id,index=0){let r=library.records.find(r=>r.id===id),imgs=photos(r),i=Math.max(0,Math.min(index,imgs.length-1)),p=imgs[i];panel(r.name+' · 图片',`<img class="album-image" src="${esc(p.url)}" alt="${p.illustration?'AI露营环境示意':'营地图片'}"><p class="panel-note">${esc(p.illustration?'AI 环境示意图，并非该营地实拍。用来还原设计稿的视觉风格，不作为现场环境、设施或天气的证据。':p.label||'营地图片')}${p.sourceUrl?` <a href="${esc(p.sourceUrl)}" target="_blank" rel="noopener noreferrer">图片来源</a>`:''}</p><div class="album-controls"><button data-album="${id}" data-index="${i-1}" aria-label="上一张" ${i===0?'disabled':''}>${icon('chevron-left')}</button><span>${i+1} / ${imgs.length}</span><button data-album="${id}" data-index="${i+1}" aria-label="下一张" ${i===imgs.length-1?'disabled':''}>${icon('chevron-right')}</button></div>`);}
function openDetail(id){if(!library)return;const r=library.records.find(x=>x.id===id);if(!r)return;lastFocus=document.activeElement;$('#detail-content').innerHTML=`<div class="detail-header"><p class="eyebrow">${esc(r.city)} · ${esc(r.type)}</p><h2 id="detail-title">${esc(r.name)}</h2><p class="detail-meta">最近采集：${r.lastCollected} · ${r.sourceIds.length} 篇来源<br>信息可信度：待核实 · 推荐分：暂不评分</p>${r.aliases.length?`<p class="detail-meta">其他写法：${esc(r.aliases.join('、'))}</p>`:''}<div class="detail-notice">下列信息来自公开笔记。请按原文日期和具体营位判断；尚未完成现场核实与现行规则确认。${r.note?`<br>${esc(r.note)}`:''}</div><div class="detail-actions"><button data-weather="${r.id}">营地天气</button><button data-season="${r.id}">观景季节</button></div></div>${r.evidence.length?r.evidence.map(e=>{const s=library.sources[e.sourceId];return `<section class="evidence"><div class="evidence-head"><h3>来自：${esc(s.author)}</h3><p>原文日期：${esc(s.date||'未显示')} · <a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">打开原文 ↗</a></p></div><dl>${e.fields.map(f=>`<div><dt>${esc(f.label)}</dt><dd>${esc(f.value)}</dd></div>`).join('')}</dl></section>`}).join(''):'<section class="evidence"><div class="evidence-head"><h3>具体详情待补充</h3><p>目前只找到合集中的地点名称。位置、费用与设施不作推断。</p></div></section>'}<section class="source-list"><h3>全部来源与日期</h3>${r.sourceIds.map(id=>{const s=library.sources[id];return `<div class="source-item"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a><p>${esc(s.author)} · ${esc(s.date||'未显示日期')}</p></div>`}).join('')}<p class="detail-meta">原文可能需要平台登录。未列出的设施表示未获取，不表示没有。</p></section>`;if(!detailDialog.open)detailDialog.showModal();document.body.classList.add('dialog-open');detailDialog.scrollTop=0;history.replaceState(null,'','#'+encodeURIComponent(id));}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.dataset.open)openDetail(b.dataset.open);else if(b.dataset.weather)weather(b.dataset.weather);else if(b.dataset.season)season(b.dataset.season);else if(b.dataset.album)album(b.dataset.album,Number(b.dataset.index)||0);});
$('#query').addEventListener('input',()=>{limit=12;render();});document.querySelectorAll('.filters select,#sort').forEach(s=>s.addEventListener('change',()=>{limit=12;render();}));document.querySelectorAll('[data-city]').forEach(b=>b.addEventListener('click',()=>{city=b.dataset.city;scope='hangzhou';document.querySelectorAll('[data-city]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));limit=12;render();}));$('#load-more').onclick=()=>{limit+=12;render();};$('#reset').onclick=()=>{city='杭州';scope='hangzhou';$('#query').value='';document.querySelectorAll('.filters select').forEach(s=>s.value='');document.querySelectorAll('[data-city]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.city===city)));limit=12;render();};$('#detail-close').onclick=()=>detailDialog.close();$('#utility-close').onclick=()=>utilityDialog.close();for(let d of [detailDialog,utilityDialog])d.addEventListener('close',()=>{if(!detailDialog.open&&!utilityDialog.open)document.body.classList.remove('dialog-open');if(d===detailDialog)history.replaceState(null,'',location.pathname+location.search);if(lastFocus?.isConnected)lastFocus.focus();});
let trip={adults:'2',gear:'自带装备',mode:'日营'};try{let t=JSON.parse(localStorage.getItem('camp-trip'));if(t&&['1','2','3','4','5','6'].includes(t.adults)&&['自带装备','租用装备'].includes(t.gear)&&['日营','过夜'].includes(t.mode))trip=t;}catch{}
function tripLabel(){$('#trip-summary').textContent=`${trip.adults}位成人 · ${trip.gear} · ${trip.mode}`;}tripLabel();$('#trip-open').onclick=()=>{panel('出行偏好',`<form id="trip-form" class="trip-form"><label>同行人数<select name="adults">${[1,2,3,4,5,6].map(n=>`<option value="${n}" ${String(n)===trip.adults?'selected':''}>${n}位成人</option>`).join('')}</select></label><label>装备<select name="gear">${['自带装备','租用装备'].map(v=>`<option ${v===trip.gear?'selected':''}>${v}</option>`).join('')}</select></label><label>行程<select name="mode">${['日营','过夜'].map(v=>`<option ${v===trip.mode?'selected':''}>${v}</option>`).join('')}</select></label><p class="panel-note">偏好保存在本机。尚未用偏好筛除营地，过夜和装备租赁是否允许请查看原文确认。</p><button class="primary" type="submit">保存偏好</button></form>`);$('#trip-form').onsubmit=e=>{e.preventDefault();let f=new FormData(e.target);trip=Object.fromEntries(f.entries());try{localStorage.setItem('camp-trip',JSON.stringify(trip));}catch{}tripLabel();utilityDialog.close();};};
$('#about-open').onclick=()=>panel('资料与图片说明',`<p>当前按来源整理杭州 ${library.counts.hangzhou} 个地点线索；其中 ${library.records.filter(r=>r.scope==='hangzhou'&&r.hasDetails).length} 处有具体介绍。名单包含公园、村落和具体营位，尚未完成逐条核实。</p><h3>资料如何判断</h3><p>推荐指数与信息可信度分开显示；证据不足时不打分。“作者称有”是来源主张，不是现行规则确认。费用保留来源口径。</p><h3>更新时间</h3><p>每周四维护，逐批复查。原文日期与采集日期单独保存，未覆盖的记录不刷新采集日期。</p><h3>图片与天气</h3><p>当前封面为AI环境示意，并非该营地实拍。相册支持最多9张，按实际数量显示，不凑张数。天气与距离暂未接入，原文链接可能需要小红书登录。</p>`);
$('#nearby-open').onclick=()=>{scope=scope==='hangzhou'?'nearby':'hangzhou';city='杭州';document.querySelectorAll('[data-city]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.city===city)));$('#query').value='';document.querySelectorAll('.filters select').forEach(s=>s.value='');limit=12;render();window.scrollTo({top:0,behavior:'auto'});};
$('#map-open').onclick=()=>panel('地图位置',`<p class="panel-note">尚未核实营地坐标。可按地点名称打开高德搜索，搜索结果需再确认具体营位。</p><div class="panel-list">${filtered().slice(0,30).map(r=>`<a href="https://uri.amap.com/search?keyword=${encodeURIComponent(r.name)}&city=${encodeURIComponent(r.city)}&view=map" target="_blank" rel="noopener noreferrer">${esc(r.name)} · 地图搜索</a>`).join('')||'<p>当前没有匹配的地点。</p>'}</div>`);
fetch('data.json').then(r=>{if(!r.ok)throw new Error('load');return r.json();}).then(data=>{library=data;$('#updated').textContent=`资料更新 ${data.updatedAt} · 每周维护`;render();if(location.hash)openDetail(decodeURIComponent(location.hash.slice(1)));}).catch(()=>{$('#error').hidden=false;$('#result-count').textContent='资料加载失败';});
