'use strict';
// External-data adapters. Each value retains its supplier, time and coordinate basis.
window.Live=(()=>{
 let config,weatherCache=new Map(),routeCache=new Map(),pending=new Map(),map,markers,routeLayer,selected,weatherDay=0,screen='list',lastPage='',observer;
 const money=n=>Number.isFinite(n)?Math.round(n):'—';
 const timeout=async(url,ms=18000)=>{const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw new Error('HTTP '+r.status);return await r.json();}finally{clearTimeout(t);}};
 const currentIcon=c=>c.weather_code===0&&c.is_day===0?'moon':code(c.weather_code)[1];
 const stamp=()=>new Date().toLocaleString('zh-CN',{hour12:false});
 const code=c=>c===0?['晴','sun']:c<=2?['多云','cloud']:c===3?['阴','cloud']:c<=48?['雾','mist']:c<=67?['雨','cloud-rain']:c<=77?['雪','cloud-snow']:c<=82?['阵雨','cloud-rain']:c<=86?['阵雪','cloud-snow']:['雷雨','cloud-storm'];
 function cacheRead(k,ttl){try{const v=JSON.parse(localStorage.getItem(k));return v&&Date.now()-v.at<ttl?v.data:null;}catch{return null;}}
 function cacheWrite(k,data){try{localStorage.setItem(k,JSON.stringify({at:Date.now(),data}));}catch{}}
 function byId(id){return library.records.find(r=>r.id===id);}
 const failedPhotos=new Set();
 function allowed(r){
  const verified=(r.images||[]).filter(p=>p.permission==='allowed'&&(/^(assets\/photos\/[a-z0-9-]+\.jpg)$/.test(p.url)||/^https:\/\//.test(p.url)));
  const refs=r.sourceIds.flatMap(sid=>{const source=library.sources[sid],rows=new Set(r.evidence.filter(e=>e.sourceId===sid).flatMap(e=>e.excelRows||[]));return (source.imageReferences||[]).filter(p=>p.review?.status==='keep'&&p.excelRows?.some(n=>rows.has(n))).map(p=>{
   const shared=library.records.some(other=>other.id!==r.id&&other.evidence.some(e=>e.sourceId===sid&&e.excelRows?.some(n=>p.excelRows.includes(n))));
   return {url:p.url.replace(/^http:\/\//,'https://')+(p.url.includes('img01.yzcdn.cn/')?'?imageView2/2/w/600':''),label:shared?'来源合集配图':r.name+' · 来源笔记配图',kind:'source',shared,author:source.author,sourceUrl:source.url,originalUrl:p.url.replace(/^http:\/\//,'https://'),sourceTitle:source.title,takenAt:null,referencedByNotes:p.referencedByNotes};
  });}).filter(p=>/^https:\/\//.test(p.url)).sort((a,b)=>Number(a.shared)-Number(b.shared)||(a.referencedByNotes||1)-(b.referencedByNotes||1));
  return [...new Map([...verified,...refs].map(p=>[p.url,p])).values()].filter(p=>!failedPhotos.has(p.url)).slice(0,9);
 }
 const photoLabel=p=>p.kind==='source'?(p.shared?'来源合集配图 · 地点待核':'来源笔记配图'):'实景 · '+(p.takenAt||'日期待补').slice(0,10);
 function nav(r){if(!r.location)return `https://uri.amap.com/search?keyword=${encodeURIComponent(r.name)}&city=杭州&view=map`;const o=config.origin,g=r.location,p=new URLSearchParams({from:`${o.longitude},${o.latitude},${o.name}`,to:`${g.longitude},${g.latitude},${r.name}`,coordinate:'wgs84',mode:'car',src:'xiuyuan-camping-guide',callnative:'0'});return 'https://uri.amap.com/navigation?'+p;}
 function photoBlock(r,priority=false){const ps=allowed(r);return ps.length?`<div class="media"><div class="slides" data-slides="${r.id}">${ps.map((p,i)=>`<button class="photo-button" data-album="${r.id}" data-index="${i}" aria-label="查看${esc(r.name)}照片第${i+1}张"><img ${i?'data-src':'src'}="${esc(p.url)}" alt="${esc(p.label)}" decoding="async" loading="${!i&&priority?'eager':'lazy'}" fetchpriority="${!i&&priority?'high':'auto'}" referrerpolicy="no-referrer"></button>`).join('')}</div><span class="image-label">${esc(photoLabel(ps[0]))}</span><span class="image-count">${icon('photo')}<span data-counter="${r.id}">1/${ps.length}</span></span>${badge(r)}</div>`:`<div class="media no-photo"><button data-album="${r.id}" class="photo-empty">${icon('photo')}<span>暂无可用营地照片</span><small>无关或失效图片已过滤</small></button>${badge(r)}</div>`;}
 function badge(r){const w=weatherCache.get(r.id);return `<button class="weather-badge" data-weather="${r.id}">${icon(w?currentIcon(w.current):'cloud')}${w?esc(code(w.current.weather_code)[0])+' '+money(w.current.temperature_2m)+'°':r.location?'天气查询中':'待核实位置'}</button>`;}
 async function getWeather(r,force=false){if(!r.location)throw new Error('营地坐标尚未核实');const g=r.location,key=`camp-weather-v1:${g.latitude.toFixed(5)},${g.longitude.toFixed(5)}`,old=!force&&cacheRead(key,20*60*1000);if(old){weatherCache.set(r.id,old);return old;}if(pending.has(key))return pending.get(key);const p=(async()=>{const u=new URL(config.providers.weather);Object.entries({latitude:g.latitude,longitude:g.longitude,current:'temperature_2m,apparent_temperature,relative_humidity_2m,weather_code,wind_speed_10m,is_day',daily:'weather_code,temperature_2m_max,temperature_2m_min,precipitation_probability_max,precipitation_sum,wind_speed_10m_max,wind_gusts_10m_max,sunrise,sunset',timezone:'Asia/Shanghai',wind_speed_unit:'ms',forecast_days:7}).forEach(([k,v])=>u.searchParams.set(k,v));const d=await timeout(u.href);if(!d.current||d.daily?.time?.length!==7)throw new Error('天气响应不完整');const v={...d,queriedAt:stamp(),requestedLocation:{...g}};weatherCache.set(r.id,v);cacheWrite(key,v);return v;})();pending.set(key,p);try{return await p;}finally{pending.delete(key);}}
 async function getRoute(r,geometry=false){if(!r.location)throw new Error('位置尚未核实');const saved=r.routeSnapshot;if((saved?.geometry||saved?.geometryUrl)&&Number.isFinite(saved.distance)&&saved.waypoints?.every(x=>x.distance<=1500)){if(geometry&&!saved.geometry){const key='geometry:'+r.id;if(!pending.has(key))pending.set(key,timeout(saved.geometryUrl).then(d=>{if(d.geometry?.type!=='LineString'||!Array.isArray(d.geometry.coordinates)||d.geometry.coordinates.length<2)throw new Error('路线文件不完整');saved.geometry=d.geometry;return saved;}).finally(()=>pending.delete(key)));await pending.get(key);}routeCache.set(r.id,saved);return saved;}const g=r.location,o=config.origin,key=`camp-route-v1:${o.longitude},${o.latitude}:${g.longitude},${g.latitude}`,cached=cacheRead(key,24*3600*1000);if(cached){routeCache.set(r.id,cached);return cached;}if(pending.has(key))return pending.get(key);const p=(async()=>{const u=config.providers.routing+`${o.longitude},${o.latitude};${g.longitude},${g.latitude}?overview=full&geometries=geojson&steps=false`;const d=await timeout(u);if(d.code!=='Ok'||!d.routes?.length)throw new Error('未找到驾车路线');if(d.waypoints.some(x=>x.distance>1500))throw new Error('路线匹配道路距参考点过远，需确认入口');const v={...d.routes[0],waypoints:d.waypoints,queriedAt:stamp(),sourceUrl:'https://project-osrm.org/',origin:o.name};routeCache.set(r.id,v);cacheWrite(key,v);return v;})();pending.set(key,p);try{return await p;}finally{pending.delete(key);}}
 const routeText=r=>{const v=routeCache.get(r.id)||r.routeSnapshot;return v?`约${(v.distance/1000).toFixed(1)}km · ${Math.round(v.duration/60)}分钟`:r.location?'路线查询中':'距离 · 车程待核';};
 function wirePhotos(root=document){root.querySelectorAll('.weather-badge[data-weather]').forEach(b=>{const r=byId(b.dataset.weather);if(!r?.location||root.id==='cards')return;getWeather(r).then(w=>{if(b.isConnected)b.innerHTML=icon(currentIcon(w.current))+esc(code(w.current.weather_code)[0])+' '+money(w.current.temperature_2m)+'°';}).catch(()=>{if(b.isConnected)b.textContent='天气暂不可用';});});root.querySelectorAll('[data-slides]').forEach(s=>{s.addEventListener('scroll',()=>{const count=s.parentElement.querySelector('[data-counter]'),idx=Math.round(s.scrollLeft/s.clientWidth),r=byId(s.dataset.slides);s.querySelectorAll('img[data-src]').forEach((image)=>{const n=Array.from(s.children).indexOf(image.parentElement);if(Math.abs(n-idx)<=1){image.src=image.dataset.src;delete image.dataset.src;}});wireImages(s);if(count)count.textContent=`${idx+1}/${s.children.length}`;const label=s.parentElement.querySelector('.image-label');if(label&&r)label.textContent=photoLabel(allowed(r)[idx]||allowed(r)[0]);},{passive:true});});wireImages(root);}
 function wireImages(root){root.querySelectorAll('.photo-button>img,.album-image,.map-preview>img').forEach(i=>{
  if(i.dataset.wired||!i.getAttribute('src'))return;i.dataset.wired='1';let timer,handled=false;
  const clear=()=>{clearTimeout(timer);if(handled)return;i.hidden=false;i.parentElement.querySelector('.image-failure')?.remove();};
  const fail=()=>{
   if(handled||!i.isConnected)return;handled=true;clearTimeout(timer);failedPhotos.add(i.getAttribute('src'));i.hidden=true;
   const slides=i.closest('[data-slides]');
   if(slides){const r=byId(slides.dataset.slides),media=slides.closest('.media'),parent=media.parentElement;media.outerHTML=photoBlock(r);wirePhotos(parent);return;}
   if(i.classList.contains('album-image')){const parts=location.hash.slice(1).split('/'),r=byId(parts[1]);if(r){albumPage(r.id,Number(parts[2])||0);return;}}
   const msg=document.createElement('span');msg.className='image-failure';msg.textContent='暂无可用图片';msg.setAttribute('role','status');i.after(msg);
  };
  i.addEventListener('load',clear);i.addEventListener('error',fail);
  const start=()=>{timer=setTimeout(()=>{if(!i.complete||!i.naturalWidth)fail();},12000);};
  if(i.complete){if(i.naturalWidth)clear();else fail();}
  else if(i.loading==='lazy'){const io=new IntersectionObserver(es=>{if(es.some(e=>e.isIntersecting)){io.disconnect();if(i.isConnected)start();}},{rootMargin:'150px'});io.observe(i);}else start();
 });}


 function hydrate(){wirePhotos($('#cards'));if(observer)observer.disconnect();const io=observer=new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting)return;io.unobserve(e.target);const r=byId(e.target.dataset.record);if(!r?.location)return;getWeather(r).then(w=>{const b=e.target.querySelector('[data-weather]');if(b)b.innerHTML=`${icon(currentIcon(w.current))}${esc(code(w.current.weather_code)[0])} ${money(w.current.temperature_2m)}°`;e.target.dataset.weather=code(w.current.weather_code)[0];}).catch(()=>{const b=e.target.querySelector('[data-weather]');if(b)b.innerHTML=icon('cloud')+'天气暂不可用';});getRoute(r).then(()=>{const s=e.target.querySelector('.route');if(s)s.innerHTML=icon('map-pin')+routeText(r);}).catch(()=>{const s=e.target.querySelector('.route');if(s)s.innerHTML=icon('map-pin')+'路线暂不可用';});}),{rootMargin:'150px'});$('#cards').querySelectorAll('[data-record]').forEach(el=>io.observe(el));}
 function setPage(type,id='',idx=''){const h=type==='list'?'':type==='map'?'map':`${type}/${id}${idx!==''?'/'+idx:''}`;if(location.hash.slice(1)===h)show();else{lastPage=location.hash.slice(1);location.hash=h;}}
 function closePage(){if(lastPage&&lastPage!==location.hash.slice(1)){const previous=lastPage;lastPage='';location.hash=previous;}else setPage('list');}
 function pageFrame(title,content){$('#live-page').hidden=false;$('#live-page').innerHTML=`<header class="page-header"><button data-back aria-label="返回">${icon('chevron-left')}</button><strong>${esc(title)}</strong><span></span></header>${content}`;$('#live-page').scrollTop=0;document.body.classList.add('live-open');window.scrollTo(0,0);}
 function detail(id){const r=byId(id);if(!r)return;pageFrame('营地详情',`${photoBlock(r)}<section class="detail-heading"><h1>${esc(r.name)}</h1><div class="rating-row"><span class="rating">${icon('star-filled')}推荐 待评</span><button class="trust" data-tab="source">信息可信度：待核</button></div><p class="environment">${esc(r.tags.join(' · ')||'环境信息待补充')}</p></section><nav class="detail-tabs"><button data-tab="overview" class="active">概览</button><button data-tab="facilities">设施</button><button data-tab="fees">费用</button><button data-tab="feedback">反馈</button></nav><div class="detail-panels">
<section data-section="overview"><h2>位置与交通</h2><p>${esc(r.area)}</p>${r.location?`<p class="location-evidence">${esc(r.location.precision)} · WGS84<br><a href="${esc(r.location.sourceUrl)}" target="_blank" rel="noopener">查看坐标来源</a></p><div id="detail-map" class="detail-map"></div><p id="detail-route">正在查询参考路线…</p><p class="fine">起点：${esc(config.origin.name)}。车程为OSRM路网估算，无实时路况；终点为区域附近可通行道路，不代表已确认营位入口。</p>`:'<p class="panel-note">具体位置尚未核实，暂不显示地图点位或该营地天气。</p>'}${evidence(r,['location','environment','hiking'])}<h2>适合谁</h2><p>${claims(r,'audience').map(esc).join('；')||'暂无可靠的人群适配介绍。'}</p><div class="detail-actions"><button data-weather="${id}">营地天气</button><button data-season="${id}">观景季节</button><button data-album="${id}">查看照片</button></div></section>
<section data-section="facilities" hidden><h2>设施与规则</h2><div class="facility-grid">${[['toilet','卫生间'],['overnight','过夜'],['stove','卡式炉 / 用火'],['parking','停车'],['utilities','水电'],['hiking','徒步路线']].map(([k,n])=>`<article><h3>${n}</h3><p>${claims(r,k).map(esc).join('；')||'待核实'}</p></article>`).join('')}</div><p class="panel-note">以上为来源主张，不代表已向营地确认的现行规则。</p></section>
<section data-section="fees" hidden><h2>费用明细</h2>${evidence(r,['fee','parking'])||'<p>费用尚未补充。不推算人均消费或套餐总价。</p>'}</section>
<section data-section="feedback" hidden><h2>真实反馈与注意事项</h2>${evidence(r,['experience','conflict'])||'<p>暂无已整理的体验反馈。</p>'}<p class="fine">包含原文摘要和已标注的表格摘录，不代表所有游客评价。</p></section>
<section data-section="source" hidden><h2>信息来源</h2><p>最近采集：${r.lastCollected}。推荐暂不评分，关键条件未完成当前核实。</p>${sources(r)}</section></div><div class="detail-bottom"><button data-tab="source">查看依据</button><a href="${esc(nav(r))}" target="_blank" rel="noopener">打开导航</a></div>`);wirePhotos($('#live-page'));if(r.location&&window.L){const m=L.map('detail-map',{scrollWheelZoom:false}).setView([r.location.latitude,r.location.longitude],13);CampMap.attach(m,{compact:true});L.marker([r.location.latitude,r.location.longitude],{title:r.name,alt:r.name}).addTo(m).bindPopup(esc(r.name));getRoute(r).then(v=>{if(selected!==id||!$('#detail-route'))return;$('#detail-route').textContent=routeText(r)+' · 路线资料 '+v.queriedAt.slice(0,10);}).catch(e=>{if($('#detail-route'))$('#detail-route').textContent='路线暂不可用：'+e.message;});}}
 function imageReferences(s){const refs=(s.imageReferences||[]).filter(p=>p.review?.status==='keep'&&/^https?:\/\//.test(p.url));if(!refs.length)return '';return `<details><summary>来源图片线索（${refs.length}条）</summary><p class="fine">来自表格，尚未核实地点归属及拍摄日期；可能含合集图片。</p><ul>${refs.map((p,i)=>`<li><a href="${esc(p.url)}" target="_blank" rel="noopener noreferrer">图片线索 ${i+1}</a>${p.referencedByNotes>1?` <small>多篇笔记共用，归属待核</small>`:''}</li>`).join('')}</ul></details>`;}
 function sources(r){return r.sourceIds.map(id=>{const s=library.sources[id];return `<div class="source-item"><a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.title)}</a><p>${esc(s.author)} · 原文 ${esc(s.date||'日期未显示')}</p>${s.spreadsheetImports?.length?`<p class="fine">含 ${esc(s.spreadsheetImports.map(x=>x.importedAt).join('、'))} 导入的表格摘录；摘录尚未复核原文。</p>`:''}${imageReferences(s)}</div>`;}).join('');}
 function evidence(r,keys){return r.evidence.map(e=>{const fs=e.fields.filter(f=>keys.includes(f.key));if(!fs.length)return '';const s=library.sources[e.sourceId];return `<article class="source-item">${e.caveat?`<p class="fine">${esc(e.caveat)}</p>`:''}${fs.map(f=>`<h3>${esc(f.label)}</h3><p>${esc(f.value)}</p>`).join('')}<a href="${esc(s.url)}" target="_blank" rel="noopener">${esc(s.author)} · ${esc(s.date)} · 原文</a></article>`;}).join('');}
 async function weatherPage(id,force=false){const r=byId(id);if(!r)return;pageFrame('营地天气',`<div class="weather-body"><h1>${esc(r.name)}</h1><p class="fine">营地附近 · 非现场监测</p><div id="weather-data"><p class="panel-note">${r.location?'正在查询当前天气与未来7天…':'具体位置尚未核实，无法准确查询营地天气。'}</p></div></div>`);if(!r.location)return;try{const w=await getWeather(r,force);if(screen!=='weather'||selected!==id)return;drawWeather(r,w);}catch(e){if($('#weather-data'))$('#weather-data').innerHTML=`<p class="panel-note">天气查询失败：${esc(e.message)}。不会显示旧值为当前天气。</p><button class="primary" data-retry-weather="${id}">重新查询</button>`;}}
 function drawWeather(r,w){const cur=w.current,d=w.daily,i=Math.min(weatherDay,d.time.length-1),text=code(cur.weather_code)[0],ic=currentIcon(cur);$('#weather-data').innerHTML=`<div class="weather-now"><div class="temperature">${icon(ic)}<strong>${money(cur.temperature_2m)}°</strong></div><p>${text} · 体感${money(cur.apparent_temperature)}°</p><small>模型时间 ${esc(cur.time.replace('T',' '))}<br>查询 ${esc(w.queriedAt)}</small></div><div class="weather-tabs"><button data-weather-mode="now">当前天气</button><button data-weather-mode="week" class="active">7天预报</button></div><div id="current-panel" hidden><div class="weather-metrics"><div>湿度<strong>${money(cur.relative_humidity_2m)}%</strong></div><div>风速<strong>${cur.wind_speed_10m}m/s</strong></div><div>体感<strong>${money(cur.apparent_temperature)}°</strong></div></div></div><div id="week-panel"><table class="forecast-table"><thead><tr><th>日期</th><th>天气</th><th>温度</th><th>日降雨概率</th></tr></thead><tbody>${d.time.map((day,n)=>`<tr class="${n===i?'chosen':''}"><td><button data-day="${n}">${n===0?'今天':n===1?'明天':new Date(day+'T12:00:00').toLocaleDateString('zh-CN',{weekday:'short'})}<small>${day.slice(5)}</small></button></td><td>${icon(code(d.weather_code[n])[1])}${code(d.weather_code[n])[0]}</td><td>${money(d.temperature_2m_min[n])}–${money(d.temperature_2m_max[n])}°</td><td>${d.precipitation_probability_max[n]??'—'}%</td></tr>`).join('')}</tbody></table></div><h2>${i===0?'今天':d.time[i]}的风雨情况</h2><div class="weather-metrics"><div>阵风<strong>${d.wind_gusts_10m_max[i]??'—'}m/s</strong></div><div>降水量<strong>${d.precipitation_sum[i]??'—'}mm</strong></div><div>全天最低<strong>${money(d.temperature_2m_min[i])}°</strong></div><div>日落<strong>${d.sunset[i]?.slice(-5)||'—'}</strong></div></div><p class="weather-alert">预报会变化，出发前再确认。<br><small>尚未接入官方预警；没有预警信息不代表安全。</small></p><p class="fine">查询点：${esc(r.location.precision)}。<br><a href="https://open-meteo.com/" target="_blank" rel="noopener">Weather data by Open-Meteo</a> · 模型估算，非营地传感器观测。</p><button class="primary" data-open="${r.id}">查看营地详情</button><button class="refresh-weather" data-retry-weather="${r.id}">刷新天气</button>`;}
 function seasonPage(id){const r=byId(id);if(!r)return;const v=claims(r,'season');pageFrame('观景季节',`<div class="season-body"><h1>${esc(r.name)}</h1><p class="fine">长期观景资料 · 不作为未来天气预报</p><div class="season-tabs"><button data-weather="${id}">天气</button><strong>观景季节</strong></div><h2>什么时候来更漂亮</h2>${allowed(r).length?photoBlock(r):'<p class="panel-note">该地点的季节实拍尚未补齐。</p>'}<p>${v.map(esc).join('；')||'尚无足够依据标注最佳月份，不统一套用春秋推荐。'}</p><h2>常年观景参考</h2><div class="months">${Array.from({length:12},(_,i)=>`<button data-month="${i+1}">${i+1}月</button>`).join('')}</div><p id="month-result" class="fine">选择月份查看已有拍摄记录；照片只证明拍摄当日的景观。</p>${evidence(r,['season'])}<button class="primary" data-weather="${id}">查看近7天天气</button></div>`);wirePhotos($('#live-page'));}
 function albumPage(id,idx=0){const r=byId(id);if(!r)return;const ps=allowed(r),i=Math.max(0,Math.min(idx,ps.length-1)),p=ps[i];pageFrame('营地照片',ps.length?`<div class="album-body"><img class="album-image" src="${esc(p.url)}" alt="${esc(p.label)}" referrerpolicy="no-referrer"><div class="album-controls"><button data-album="${id}" data-index="${i-1}" ${i===0?'disabled':''} aria-label="上一张">${icon('chevron-left')}</button><span>${i+1} / ${ps.length}</span><button data-album="${id}" data-index="${i+1}" ${i===ps.length-1?'disabled':''} aria-label="下一张">${icon('chevron-right')}</button></div><h2>${esc(p.label)}</h2>${p.kind==='source'?`<p>来源笔记：${esc(p.sourceTitle)}<br>笔记作者：${esc(p.author)}<br>拍摄日期：原表未提供</p><p class="panel-note">${p.shared?'该图来自包含多个地点的来源笔记，具体拍摄地点待核。':'用户提供的笔记配图，具体拍摄地点与日期尚未复核。'}</p>`:`<p>拍摄日期：${esc(p.takenAt)}<br>作者：${esc(p.author)}</p><p>${esc(p.description)}</p><p class="panel-note">真实历史照片，不是实时画面；公园景观不代表已确认的露营营位。</p>`}<a href="${esc(p.originalUrl)}" target="_blank" rel="noopener">查看原图</a> · <a href="${esc(p.sourceUrl)}" target="_blank" rel="noopener">图片来源</a>${p.kind==='source'?'':`<p><a href="${esc(p.licenseUrl)}" target="_blank" rel="noopener">${esc(p.license)}</a> · 展示裁切，原图未修改</p>`}</div>`:`<div class="album-body"><p class="panel-note">暂无可用营地照片；无关、重复归属或失效图片已过滤。</p>${sources(r)}</div>`);wireImages($('#live-page'));}
 function showMap(){if(!config.providers.basemap||!window.L||!window.CampMap){pageFrame('地图','<p class="panel-note">地图组件加载失败，请刷新后重试。</p>');return;}document.body.classList.add('map-mode');$('#map-view').hidden=false;$('#map-open').innerHTML=icon('users')+'列表';$('#map-open').setAttribute('aria-label','返回列表');if(!map){map=L.map('camp-map',{zoomControl:false}).setView([30.22,120.1],11);L.control.zoom({position:'bottomright'}).addTo(map);CampMap.attach(map);markers=L.layerGroup().addTo(map);}map.invalidateSize();updateMap(true);}
 function updateMap(fit=false){if(!map)return;markers.clearLayers();const rs=filtered().filter(r=>r.location);$('#map-status').textContent=`已定位 ${rs.length} / ${filtered().length} 处 · 均为区域参考点`;rs.forEach((r,i)=>{L.marker([r.location.latitude,r.location.longitude],{title:r.name,alt:r.name,icon:L.divIcon({className:'camp-map-pin',html:'<span>'+String(i+1)+'</span>',iconSize:[26,26],iconAnchor:[13,13]})}).addTo(markers).bindTooltip(esc(r.name),{direction:'top',permanent:true,className:'camp-pin-label',offset:[0,-10]}).on('click',()=>selectMap(r.id));});if(rs.length){if(fit)map.fitBounds(rs.map(r=>[r.location.latitude,r.location.longitude]),{paddingTopLeft:[28,85],paddingBottomRight:[28,240],maxZoom:13});selectMap(rs.some(r=>r.id===selected)?selected:rs[0].id);}else $('#map-selection').innerHTML='<p>当前筛选没有已定位的地点。</p>';}
 function selectMap(id){if(selected!==id&&routeLayer){map.removeLayer(routeLayer);routeLayer=null;}selected=id;const r=byId(id),p=allowed(r)[0];const fallback=$('#camp-map .basemap-notice a');if(fallback)fallback.href=nav(r);$('#map-selection').innerHTML=`<div class="map-sheet-top"><strong>${esc(r.name)}</strong><button id="collapse-map">收起</button></div><div class="map-preview">${p?`<img src="${esc(p.url)}" alt="${esc(p.label)}" referrerpolicy="no-referrer">`:''}<div><p>${esc(r.tags.join(' · ')||r.type)}</p><span class="rating">推荐 待评</span><p id="map-route">${routeText(r)}</p><small>${esc(r.location.precision)}</small></div></div><div class="map-sheet-actions"><button class="primary" data-open="${id}">查看营地详情</button><a href="${esc(nav(r))}" target="_blank" rel="noopener">导航</a><button data-route-map="${id}">路线</button></div>`;wireImages($('#map-selection'));$('#collapse-map').onclick=()=>{$('#map-selection').classList.toggle('collapsed');$('#collapse-map').textContent=$('#map-selection').classList.contains('collapsed')?'展开':'收起';};getRoute(r).then(()=>{if(selected===id&&$('#map-route'))$('#map-route').textContent=routeText(r);}).catch(()=>{if($('#map-route'))$('#map-route').textContent='路线暂不可用';});}
 async function showRoute(id){const r=byId(id);try{const d=await getRoute(r,true);if(routeLayer)map.removeLayer(routeLayer);routeLayer=L.geoJSON(d.geometry,{style:{color:'#20584a',weight:5}}).addTo(map);L.circleMarker([config.origin.latitude,config.origin.longitude],{radius:5,color:'#fff',weight:2,fillColor:'#20584a',fillOpacity:1}).addTo(routeLayer).bindTooltip('武林广场出发',{permanent:true,direction:'top',className:'camp-pin-label'});map.fitBounds(routeLayer.getBounds(),{paddingTopLeft:[30,85],paddingBottomRight:[30,240]});$('#map-status').textContent=`${config.origin.name}出发 · ${routeText(r)} · 参考路线 ${d.queriedAt.slice(0,10)}`;}catch(e){$('#map-status').textContent=e.message;}}
 function show(){if(!library)return;const parts=decodeURIComponent(location.hash.slice(1)).split('/'),type=parts[0]||'list',id=parts[1];document.body.classList.remove('live-open','map-mode');$('#live-page').hidden=true;$('#map-view').hidden=true;$('#map-open').innerHTML=icon('map-2')+'地图';$('#map-open').removeAttribute('aria-label');screen=type;selected=id||selected;if(type==='map')showMap();else if(type==='camp'||/^C\d+$/.test(type))detail(id||type);else if(type==='weather'){weatherDay=0;weatherPage(id);}else if(type==='season')seasonPage(id);else if(type==='photos')albumPage(id,Number(parts[2])||0);if(type!=='list'&&type!=='map'&&!byId(id||type))pageFrame('地点未找到','<p class="panel-note">该分享链接中的地点不存在，请返回列表搜索。</p>');}
 async function init(data){try{config=await timeout('live-data.json?v='+($('meta[name=camp-live-version]')?.content||'6'),10000);for(const r of data.records){const live=config.records[r.id];if(live)Object.assign(r,live);}}catch(e){config={origin:{name:'杭州武林广场'},providers:{},records:{}};$('#live-status').textContent='扩展数据加载失败，地图与天气暂不可用';}window.addEventListener('hashchange',()=>{show();});document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-back')){if(screen==='photos'&&lastPage.startsWith('photos/'))setPage('camp',selected);else closePage();}if(b.dataset.tab){document.querySelectorAll('[data-section]').forEach(s=>s.hidden=s.dataset.section!==b.dataset.tab);document.querySelectorAll('.detail-tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===b.dataset.tab));}if(b.dataset.retryWeather)weatherPage(b.dataset.retryWeather,true);if(b.dataset.day!==undefined){weatherDay=Number(b.dataset.day);drawWeather(byId(selected),weatherCache.get(selected));}if(b.dataset.weatherMode){$('#current-panel').hidden=b.dataset.weatherMode!=='now';$('#week-panel').hidden=b.dataset.weatherMode!=='week';document.querySelectorAll('[data-weather-mode]').forEach(x=>x.classList.toggle('active',x===b));}if(b.dataset.routeMap)showRoute(b.dataset.routeMap);if(b.dataset.month){const r=byId(selected),n=Number(b.dataset.month),matches=allowed(r).filter(p=>p.takenAt&&new Date(p.takenAt).getMonth()+1===n);$('#month-result').textContent=matches.length?`${n}月有${matches.length}张历史照片；可在相册核对日期，尚未评为最佳月份。`:`暂无${n}月的可核实观景记录。`;}});$('#map-open').onclick=()=>setPage(screen==='map'?'list':'map');$('#search-map-area').onclick=()=>{const visible=filtered().filter(r=>r.location&&map.getBounds().contains([r.location.latitude,r.location.longitude]));$('#map-status').textContent=`当前地图区域 ${visible.length} 处已收录地点`;if(visible.length)selectMap(visible[0].id);};$('#map-fit').onclick=()=>updateMap(true);if(Object.keys(config.records).length)$('#live-status').textContent=`地图点位 ${Object.keys(config.records).length} 处 · 天气按位置查询`;}
 return {init,hydrate,photoBlock,allowed,badge,routeText,nav,getWeather,getRoute,show,showMap,updateMap,setPage,code,weatherCache,routeCache};
})();
